version: '3.9'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret#1
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./scripts/pg-init-script.sh:/docker-entrypoint-initdb.d/pg-init-script.sh

volumes:
  db:
    driver: local
