apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.dbPort }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres
